$ErrorActionPreference = 'Continue'
# 本机用户目录（默认取当前用户；也可以先 $env:USER_HOME 指定）
$USER_HOME = if ($env:USER_HOME) { $env:USER_HOME } else { $env:USERPROFILE }

$dest = 'E:\DeepSeekHarness\home\skills'
New-Item -ItemType Directory -Force -Path $dest | Out-Null
$ok = 0; $skip = 0; $fail = 0
if (Test-Path -LiteralPath (Join-Path $dest 'skill-creator')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'skill-creator') -Target "$USER_HOME\.codex\skills\.system\skill-creator" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL skill-creator: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'academic-research-suite')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'academic-research-suite') -Target "$USER_HOME\.codex\skills\academic-research-suite" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL academic-research-suite: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'docx')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'docx') -Target "$USER_HOME\.codex\skills\docx" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL docx: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'humanize-mba-text')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'humanize-mba-text') -Target "$USER_HOME\.codex\skills\humanize-mba-text-skill" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL humanize-mba-text: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'humanizer')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'humanizer') -Target "$USER_HOME\.codex\skills\humanizer" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL humanizer: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'humanizer-zh')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'humanizer-zh') -Target "$USER_HOME\.codex\skills\humanizer-zh" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL humanizer-zh: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'kimi-vision')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'kimi-vision') -Target "$USER_HOME\.codex\skills\kimi-vision" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL kimi-vision: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'kunpeng-skill')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'kunpeng-skill') -Target "$USER_HOME\.codex\skills\kunpeng-skill" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL kunpeng-skill: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-academic-search')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-academic-search') -Target "$USER_HOME\.codex\skills\nature-academic-search" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-academic-search: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-citation')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-citation') -Target "$USER_HOME\.codex\skills\nature-citation" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-citation: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-figure')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-figure') -Target "$USER_HOME\.codex\skills\nature-figure" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-figure: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-paper2ppt')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-paper2ppt') -Target "$USER_HOME\.codex\skills\nature-paper2ppt" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-paper2ppt: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-polishing')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-polishing') -Target "$USER_HOME\.codex\skills\nature-polishing" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-polishing: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-response')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-response') -Target "$USER_HOME\.codex\skills\nature-response" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-response: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-reviewer')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-reviewer') -Target "$USER_HOME\.codex\skills\nature-reviewer" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-reviewer: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-shared')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-shared') -Target "$USER_HOME\.codex\skills\nature-shared" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-shared: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'nature-writing')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'nature-writing') -Target "$USER_HOME\.codex\skills\nature-writing" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL nature-writing: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'ppt-master')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'ppt-master') -Target "$USER_HOME\.codex\skills\ppt-master" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL ppt-master: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'scibox-diagram')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'scibox-diagram') -Target "$USER_HOME\.codex\skills\scibox-diagram" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL scibox-diagram: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'mathmodel-figure-templates')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'mathmodel-figure-templates') -Target "$USER_HOME\.codex\skills\scibox-figure" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL mathmodel-figure-templates: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'thesis-defense-pptx')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'thesis-defense-pptx') -Target "$USER_HOME\.codex\skills\thesis-defense-pptx" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL thesis-defense-pptx: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'officecli')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'officecli') -Target "$USER_HOME\.agents\skills\officecli" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL officecli: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'officecli-academic-paper')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'officecli-academic-paper') -Target "$USER_HOME\.agents\skills\officecli-academic-paper" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL officecli-academic-paper: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'officecli-docx')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'officecli-docx') -Target "$USER_HOME\.agents\skills\officecli-docx" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL officecli-docx: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'brainstorming')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'brainstorming') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\brainstorming" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL brainstorming: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'dispatching-parallel-agents')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'dispatching-parallel-agents') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\dispatching-parallel-agents" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL dispatching-parallel-agents: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'executing-plans')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'executing-plans') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\executing-plans" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL executing-plans: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'finishing-a-development-branch')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'finishing-a-development-branch') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\finishing-a-development-branch" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL finishing-a-development-branch: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'receiving-code-review')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'receiving-code-review') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\receiving-code-review" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL receiving-code-review: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'requesting-code-review')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'requesting-code-review') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\requesting-code-review" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL requesting-code-review: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'subagent-driven-development')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'subagent-driven-development') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\subagent-driven-development" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL subagent-driven-development: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'systematic-debugging')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'systematic-debugging') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\systematic-debugging" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL systematic-debugging: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'test-driven-development')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'test-driven-development') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\test-driven-development" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL test-driven-development: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'using-git-worktrees')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'using-git-worktrees') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\using-git-worktrees" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL using-git-worktrees: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'using-superpowers')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'using-superpowers') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\using-superpowers" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL using-superpowers: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'verification-before-completion')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'verification-before-completion') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\verification-before-completion" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL verification-before-completion: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'writing-plans')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'writing-plans') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\writing-plans" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL writing-plans: ' + $_.Exception.Message) } }
if (Test-Path -LiteralPath (Join-Path $dest 'writing-skills')) { $skip++ } else { try { New-Item -ItemType Junction -Path (Join-Path $dest 'writing-skills') -Target "$USER_HOME\.codex\plugins\cache\openai-api-curated\superpowers\1dc19589\skills\writing-skills" | Out-Null; $ok++ } catch { $fail++; Write-Host ('FAIL writing-skills: ' + $_.Exception.Message) } }
Write-Host ("created=$ok existed=$skip failed=$fail")